### ISSUE TITLE
 没有生成这个目录 \RssBot\data.json

### ISSUE THREAD

**Issue by NoteKami** [NiTian1207/RssBot#1]

**Comment by NiTian1207** [comment]
在config文件夹下

**Comment by NoteKami** [comment]
也没有。

**Comment by NoteKami** [comment]
> 在config文件夹下

也没有。。

**Comment by NiTian1207** [comment]
> > 在config文件夹下
> 
> 也没有。。

那你手动创建这个文件夹再运行试试

**Comment by NoteKami** [comment]
> > > 在config文件夹下
> > 
> > 
> > 也没有。。
> 
> 那你手动创建这个文件夹再运行试试
手动建立后，正常生成。解决了。谢谢大大ovo
